package org.geysermc.mappings.generator;

import net.minecraft.SharedConstants;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.PackOutput;
import org.geysermc.mappings.FileType;
import org.geysermc.mappings.util.MappingsUtil;

import java.util.concurrent.CompletableFuture;

public final class ReadMeGenerator extends MappingsGenerator<String> {
    private static final String BASE = """
# mappings

These files contain Minecraft Java <-> Bedrock mappings and other data used in projects of GeyserMC. These files were generated by GeyserMC's [mappings-generator](https://github.com/GeyserMC/mappings-generator);
please refer to the README there for a throughout description of these files.

These files were generated for Minecraft: Java Edition %s and Minecraft: Bedrock Edition %s.

These files are licensed by GeyserMC under the MIT license. Please note that GeyserMC only licenses the original work contributors have the right to license.
GeyserMC does not relicense Minecraft, its data, or any other material owned by Mojang or Microsoft.
""";

    public ReadMeGenerator(PackOutput output) {
        super(output, FileType.README);
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        return saveFile(cache, BASE.formatted(SharedConstants.getCurrentVersion().name(), MappingsUtil.getHumanBedrockVersion()));
    }

    @Override
    public String getName() {
        return "README generator";
    }
}
